version: '2'
services:
  redis:
    restart: always
    image: redis
    volumes:
    - ./data:/data/
    container_name: redis
    command: redis-server --appendonly yes --protected-mode no --save 60 1
  frontend:
    restart: always
    build: ./canarytokens/
    image: thinkst/canarytokens
    links:
     - redis
    env_file:
     - frontend.env
    volumes:
    - ./uploads:/uploads/
    container_name: frontend
    command: bash -c "rm frontend.pid; twistd -noy frontend.tac --logger log.logger --pidfile=frontend.pid"
  switchboard:
    build: ./canarytokens/
    restart: always
    image: thinkst/canarytokens
    ports:
     - "53:53"
     - "53:53/udp"
     - "25:25"
    links:
     - redis
    env_file:
     - switchboard.env
    volumes_from:
    - frontend
    container_name: switchboard
    command: bash -c "rm switchboard.pid; twistd -noy switchboard.tac --logger log.logger --pidfile=switchboard.pid"
  nginx:
    restart: always
    build: nginx-image
    ports:
     - "80:80"
     - "443:443"
    links:
     - frontend
     - switchboard
     - letsencrypt
    container_name: nginx
    volumes_from:
      - letsencrypt
    environment:
      - MY_DOMAIN_NAME=thinkst.com

  letsencrypt:
    image: quay.io/letsencrypt/letsencrypt:latest
    container_name: letsencrypt
    command:  bash -c "sleep 6 && certbot certonly --standalone -d thinkst.com --text --agree-tos --email info@thinkst.com --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --renew-by-default --standalone-supported-challenges http-01"
    entrypoint: ""
    volumes:
      - /etc/letsencrypt
      - /var/lib/letsencrypt
    ports:
      - "80"
      - "443"
